version: "3.8"

services:
  postgres:
    image: ankane/pgvector
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

  localai:
    image: localai/localai:latest-aio-cpu
    ports:
      - "8080:8080"
    volumes:
      - ./models:/build/models
    environment:
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_PORT=8000
    restart: always

  api-admin:
    build:
      context: .
      dockerfile: docker/Dockerfile.api-admin
    ports:
      - "8500:8500"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/db
      - ADMIN_SECRET=your-admin-secret-key
    volumes:
      - ./apps/backend/admin-api:/app
    depends_on:
      - postgres
    restart: unless-stopped

  jena-fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ./backend/jena-fuseki:/fuseki

  flowise:
    image: flowiseai/flowise
    restart: always
    ports:
      - "3000:3000"
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=secret
    volumes:
      - ./backend/flowise:/root/.flowise

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./backend/reverse-proxy/data:/data
      - ./backend/reverse-proxy/letsencrypt:/etc/letsencrypt

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8081:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    restart: unless-stopped

volumes:
  pgdata:
  open-webui-data: