version: "3.8"

services:
  postgres:
    image: ankane/pgvector
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

  localai:
    image: localai/localai:latest-aio-cpu
    ports:
      - "8080:8080"
    volumes:
      - ./models:/build/models
    environment:
      - DEBUG=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_PORT=8000
    restart: always

  api-admin:
    build:
      context: .
      dockerfile: docker/Dockerfile.api-admin
    ports:
      - "8500:8500"
    restart: unless-stopped

  flowise:
    image: flowiseai/flowise
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./apps/backend/api/backend/flowise:/root/.flowise

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ./apps/backend/api/backend/jena-fuseki:/fuseki

  nginx:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./infra/nginx/data:/data
      - ./infra/nginx/letsencrypt:/etc/letsencrypt

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8081:8080"
    volumes:
      - ./apps/backend/api/backend/open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  pgdata: